import { useState } from "react";
import "./BlogDetails.css";
import cloud from "../assets/cloud.jpg";
import { motion } from "framer-motion";
import ScrollReveal from "../components/ScrollReveal";

const cardVariants = {
  hidden: { opacity: 0, y: 40 },
  show: (i) => ({
    opacity: 1,
    y: 0,
    transition: {
      delay: i * 0.15,
      duration: 0.6
    }
  })
};


const Computing = () => {
    // ✅ reactions state
    const [reactions, setReactions] = useState({
      heart: 0,
      like: 0,
      sad: 0,
      cry: 0,
    });
  
    // ✅ handle reaction click
    const handleReaction = (type) => {
      setReactions((prev) => ({
        ...prev,
        [type]: prev[type] + 1,
      }));
    };
  
    // ✅ share functions
    const handleWhatsAppShare = () => {
      const url = window.location.href;
      window.open(`https://wa.me/?text=${encodeURIComponent(url)}`, "_blank");
    };
  
    const handleLinkedInShare = () => {
      const url = window.location.href;
      window.open(
        `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`,
        "_blank"
      );
    };
  
    const handleCopyLink = () => {
      navigator.clipboard.writeText(window.location.href);
      alert("Link copied!");
    };

  return (
    <div className="page">

      <h1 className="title">
        The Rise of Edge Computing
      </h1>

      <ScrollReveal>
      <img
        src={cloud}
        alt="Edge Computing"
        className="blog-image"
      />
      </ScrollReveal>

      <p className="para">
        Edge computing is rapidly transforming the way organizations process and manage data.
        Traditionally, data generated by devices was sent to centralized cloud servers for
        processing and analysis. While cloud computing remains essential, the growing demand
        for real-time applications has created new challenges related to latency, bandwidth,
        and reliability. Edge computing addresses these challenges by bringing computation
        and data storage closer to the source of data generation. By processing information
        near users and devices, businesses can deliver faster responses, reduce network
        congestion, and improve overall system performance.
      </p>

      <p className="quote">
        “The future of computing is not only in the cloud — it is at the edge, where data is created and decisions are made in real time.”
      </p>

      <h2 className="h2">What is Edge Computing?</h2>

      <p className="para">
        Edge computing is a distributed computing model that processes data closer to the
        devices and users generating it rather than relying entirely on centralized cloud
        infrastructure. This approach minimizes the distance data must travel, significantly
        reducing latency and enabling faster decision-making. Edge devices can include IoT
        sensors, smartphones, autonomous vehicles, industrial machines, and smart cameras.
        As organizations increasingly rely on connected technologies, edge computing has
        become a critical component of modern digital infrastructure.
      </p>

      <h2 className="h2">Key Benefits of Edge Computing</h2>

      <ScrollReveal>

      <div className="industry-grid">

        <div className="industry-card">
          <h3>⚡ Low Latency</h3>
          <p>
            Data is processed closer to users, enabling faster
            responses for real-time applications.
          </p>
        </div>

        <div className="industry-card">
          <h3>📶 Reduced Bandwidth</h3>
          <p>
            Less data needs to travel to cloud servers,
            reducing network traffic and costs.
          </p>
        </div>

        <div className="industry-card">
          <h3>🔒 Better Security</h3>
          <p>
            Sensitive information can remain closer to its
            source, improving data protection.
          </p>
        </div>

        <div className="industry-card">
          <h3>🚀 Improved Performance</h3>
          <p>
            Applications become more responsive and reliable
            even in remote locations.
          </p>
        </div>

      </div>
      </ScrollReveal>

      <h2 className="h2">Edge Computing in Real-World Applications</h2>

      <p className="para">
        Edge computing powers many technologies that require immediate decision-making.
        Autonomous vehicles use edge systems to process sensor data instantly and react
        to road conditions without waiting for cloud responses. Smart cities leverage edge
        computing for traffic management, surveillance systems, and public safety monitoring.
        In healthcare, medical devices use edge processing to analyze patient data in real
        time and support critical clinical decisions. Manufacturing industries also use
        edge-enabled systems to monitor equipment performance and predict maintenance needs.
      </p>

      <h2 className="h2">Industries Driving Adoption</h2>
      <ScrollReveal>

      <div className="industry-grid">

        <div className="industry-card">
          <h3>🏭 Manufacturing</h3>
          <p>
            Real-time monitoring and predictive maintenance
            improve operational efficiency.
          </p>
        </div>

        <div className="industry-card">
          <h3>🚗 Transportation</h3>
          <p>
            Autonomous vehicles and smart traffic systems
            rely on edge processing.
          </p>
        </div>

        <div className="industry-card">
          <h3>🏥 Healthcare</h3>
          <p>
            Medical devices can process patient data
            instantly for faster diagnosis.
          </p>
        </div>

        <div className="industry-card">
          <h3>🏙 Smart Cities</h3>
          <p>
            Edge systems help manage infrastructure,
            security, and public services efficiently.
          </p>
        </div>

      </div>
      </ScrollReveal>

      <h2 className="h2">Challenges of Edge Computing</h2>

      <p className="para">
        Despite its advantages, edge computing introduces several challenges. Managing
        thousands of distributed devices can be complex and requires robust monitoring
        systems. Security risks increase as more devices become connected to networks.
        Organizations must also ensure consistent software updates and maintenance across
        multiple edge locations. Additionally, integrating edge infrastructure with
        existing cloud platforms requires careful planning and investment.
      </p>

      <h2 className="h2">The Future of Edge Computing</h2>

      <p className="para">
        The future of edge computing is closely connected to the growth of 5G networks,
        artificial intelligence, and the Internet of Things. Faster connectivity and
        smarter devices will enable organizations to process data more efficiently than
        ever before. Businesses will increasingly adopt hybrid architectures that combine
        the scalability of cloud computing with the speed of edge computing. As digital
        transformation continues, edge computing will play a central role in delivering
        intelligent, responsive, and scalable technology solutions.
      </p>

      <h2 className="h2">Conclusion</h2>

      <p className="para">
        Edge computing is redefining how data is processed in a connected world. By moving
        computation closer to users and devices, organizations can reduce latency, improve
        performance, and support innovative applications that require real-time responses.
        As technologies such as AI, IoT, and 5G continue to evolve, edge computing will
        become an essential pillar of modern digital infrastructure, enabling smarter and
        more efficient systems across industries.
      </p>

       {/* ===================== REACTIONS ===================== */}
      <div className="reaction-box">
        <h3>React to this article</h3>

        <div className="reactions">
          <button onClick={() => handleReaction("heart")}>
            ❤️ {reactions.heart}
          </button>

          <button onClick={() => handleReaction("like")}>
            👎 {reactions.like}
          </button>

          <button onClick={() => handleReaction("sad")}>
            😢 {reactions.sad}
          </button>

          <button onClick={() => handleReaction("cry")}>
            😭 {reactions.cry}
          </button>
        </div>
      </div>

      {/* ===================== SHARE ===================== */}
      <div className="share-box">
        <h3>Share this article</h3>

        <div className="share-buttons">
          <button onClick={handleWhatsAppShare}>
            📱 WhatsApp
          </button>

          <button onClick={handleLinkedInShare}>
            💼 LinkedIn
          </button>

          <button onClick={handleCopyLink}>
            🔗 Copy Link
          </button>
        </div>
      </div>

    </div>
  );
};

export default Computing;

